os:
  - linux

language: node_js

node_js:
  - node

cache:
  directories:
  - $HOME/.yarn-cache

before_install:
  - npm install -g --silent yarn

install:
  - yarn

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js